---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  galaxy:
    collections:
      - { name: community.general, version: 9.5.0 }
      - { name: ansible.utils, version: 4.1.0 }

options:
  package_manager_path: /usr/bin/microdnf
